<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AegisAuth.Application/AegisAuth.Application.csproj" />
    <ProjectReference Include="../AegisAuth.Domain/AegisAuth.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data/" />
    <Folder Include="Data/Configurations/" />
    <Folder Include="Data/Context/" />
    <Folder Include="Services/" />
  </ItemGroup>

</Project>
