<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AegisAuth.Application/AegisAuth.Application.csproj" />
    <ProjectReference Include="../AegisAuth.Domain/AegisAuth.Domain.csproj" />
    <ProjectReference Include="../AegisAuth.Infrastructure/AegisAuth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
